// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    IMinesweeper: typeof import('./src/components/IMinesweeper.vue')['default']
    MinesweeperAside: typeof import('./src/components/MinesweeperAside.vue')['default']
    MinesweeperWindow: typeof import('./src/components/MinesweeperWindow.vue')['default']
  }
}
